server:
  port: 8081

app:
  base-url: http://localhost:8081

spring:
  application:
    name: shippingapp
  database:
    url: r2dbc:postgresql://localhost:5432
    schema: shippingapp
    username: postgres
    password: postgres
    pool:
      max-size: 20
      max-idle-minutes: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    modulo: 2
    servicio: shipping-app